Spdif Transmit refresh
xmos/lib_spdif pull request #43
Opened 2023-03-29 14:20 UTC by TDW89

Update and refresh of SpdifTransmit.xc along with some tidy up of externally referenced header files (should now be using the api file)

2023-03-29 15:35 UTC, xross requested changes

2023-03-30 09:28 UTC, xross commented
SpdifTransmit.xc has inconsistent indentation - sometimes two spaces, sometimes four

2023-04-05 10:10 UTC, xross requested changes

2023-04-05 10:10 UTC, xross commented on lib_spdif/api/spdif.h
> +void SpdifReceive(in buffered port:4 p, streaming chanend c, int initial_divider, clock clk);
This one still needs addressing

2023-04-05 16:44 UTC, TDW89 commented on lib_spdif/api/spdif.h
> +void SpdifReceive(in buffered port:4 p, streaming chanend c, int initial_divider, clock clk);
should be sorted

2023-04-05 16:44 UTC, TDW89 commented on lib_spdif/src/SpdifTransmit.xc
>  /**
fixed

2023-04-05 16:48 UTC, xross commented
Looks good, I quickly scanned the documentation and didn't see any updated that were required but would be good to get a second set of eyes to look over it.

2023-04-05 16:49 UTC, xross approved these changes

2023-04-05 16:49 UTC, merged